#ifndef VITAMATERIALKIT_ICONSCODES_PSVITA_HH
#define VITAMATERIALKIT_ICONSCODES_PSVITA_HH

#pragma once

#define ICON_PSVITA_MAJ "A"
#define ICON_PSVITA_KEYBOARD "B"
#define ICON_PSVITA_ENTER "C"
#define ICON_PSVITA_PLAYSTATION "D"
#define ICON_PSVITA_DNAS "E"
#define ICON_PSVITA_ATRAC "F"
#define ICON_PSVITA_PSPLUS "G"

#define ICON_PSVITA_LTRIGGER "0"
#define ICON_PSVITA_RTRIGGER "1"
#define ICON_PSVITA_LSTICK "2"
#define ICON_PSVITA_RSTICK "3"
#define ICON_PSVITA_SELECT "4"
#define ICON_PSVITA_START "5"
#define ICON_PSVITA_PSBUTTON "6"
#define ICON_PSVITA_POWER "7"
#define ICON_PSVITA_VOLUP "8"
#define ICON_PSVITA_VOLDOWN "9"

#define ICON_PSVITA_TRIANGLE " "
#define ICON_PSVITA_CIRCLE "!"
#define ICON_PSVITA_CROSS "\""
#define ICON_PSVITA_SQUARE "#"
#define ICON_PSVITA_TRIANGLE_BUTTON_HOLD "$"
#define ICON_PSVITA_CIRCLE_BUTTON_HOLD "%"
#define ICON_PSVITA_CROSS_BUTTON_HOLD "&"
#define ICON_PSVITA_SQUARE_BUTTON_HOLD "'"
#define ICON_PSVITA_TRIANGLE_BUTTON_PRESS "("
#define ICON_PSVITA_CIRCLE_BUTTON_PRESS ")"
#define ICON_PSVITA_CROSS_BUTTON_PRESS "*"
#define ICON_PSVITA_SQUARE_BUTTON_PRESS "+"

#define ICON_PSVITA_UP ","
#define ICON_PSVITA_DOWN "-"
#define ICON_PSVITA_LEFT "."
#define ICON_PSVITA_RIGHT "/"

#define ICON_PSVITA_USB ":"
#define ICON_PSVITA_SELFTIMER_HALF ";"
#define ICON_PSVITA_SELFTIMER_END "<"
#define ICON_PSVITA_WELCOME "="
#define ICON_PSVITA_PIN ">"
#define ICON_PSVITA_TAB "@"

#endif //VITAMATERIALKIT_ICONSCODES_PSVITA_HH
