#ifndef VITAMATERIALKIT_CONFIG_HH
#define VITAMATERIALKIT_CONFIG_HH

#define VMKIT_VERSION 0.7
#define DEBUG_APP 0
#define SCREEN_WIDTH 960
#define SCREEN_HEIGHT 544
#define SCREEN_HALF_WIDTH SCREEN_WIDTH/2
#define SCREEN_HALF_HEIGHT SCREEN_HEIGHT/2

#endif //VITAMATERIALKIT_CONFIG_HH
